#!/usr/bin/env python3
"""Multiverse Achaean Media Pipeline.

Two-pronged polite ingestion into ./achaeans_curated_library:

  Phase A ("art")   — Wikimedia Commons: resolve each File: title via the
                      MediaWiki Action API, then download the original.
  Phase B ("films") — Internet Archive: query each item's file manifest first,
                      download only companion images + the smallest usable MP4.
  Phase C ("clips") — Cut short clips from the downloaded MP4s with ffmpeg.
                      Runs ONLY for specs whose `start` timestamp has been set
                      (they ship as None so nobody cuts blind at 0:00).

  Phase 0 ("verify")   — resolve every manifest title via the API, download
                         NOTHING. The manifest titles were generated by an LLM
                         (Gemini) and are unverified guesses — run this first.
  Phase D ("discover") — keyword search of Commons, filtered to PD/CC-usable
                         licenses; writes a candidate manifest for review,
                         downloads NOTHING. Use it to repair MISSING manifest
                         titles or to scout new subjects.

  Phase E ("dedupe")   — no-duplicates audit: identity collisions across term
                         manifests, matches against the live glossary's
                         art.json, and a dHash+aHash perceptual sweep (the
                         thresholds proven on tellmeohmuse). Network-free.
                         Arrival-time PREVENTION is separate: the art phase
                         refuses downloads via the library ledger + glossary
                         gates before any bytes move.

Usage:
    python pipeline.py verify             # resolve manifest titles, no downloads
    python pipeline.py seed-ledger        # load the live glossary's Commons
                                          # identities into the ledger gate
    python pipeline.py                    # art + films (clips skipped until timed)
    python pipeline.py art
    python pipeline.py films
    python pipeline.py clips              # after filling in CLIP_SPECS timestamps
    python pipeline.py all
    python pipeline.py discover "mycenaean warrior"   # candidate manifest only
    python pipeline.py discover --terms-file terms.txt
    python pipeline.py select "Mask of Agamemnon"   # score + montage the top
                                          # candidates of one term's manifest
    python pipeline.py dedupe             # audit after every harvest batch

Politeness standard (mandatory, do not loosen):
  * 2.5 s sleep between EVERY remote request — API pings included.
  * Every download is skip-if-exists, so an interrupted re-run makes zero
    duplicate connections.
  * One explicit descriptive User-Agent on every Commons request.
"""

from __future__ import annotations  # lazy annotations: works on Python 3.9

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

import requests

try:
    import internetarchive as ia
except ImportError:
    ia = None  # only needed for the films phase; fail there with a clear message

# ── Configuration ────────────────────────────────────────────────────────────

PIPELINE_DIR = Path(__file__).resolve().parent
OUTPUT_DIRECTORY = PIPELINE_DIR / "achaeans_curated_library"
CLIPS_DIRECTORY = OUTPUT_DIRECTORY / "clips"
DISCOVERY_DIRECTORY = OUTPUT_DIRECTORY / "discovery"

POLITENESS_DELAY_SECONDS = 2.5

# Appropriate resolution: plenty for lightbox zoom, far short of the raw
# museum scans. Originals wider than this are fetched as Commons-rendered
# derivatives at this width instead (the ledger still records the ORIGINAL's
# sha1/pageid, so identity gating is unaffected by which rendition landed).
MAX_LONG_EDGE = 3200

USER_AGENT = (
    "AchaeanDataPipeline/2.0 (bahinton@gmail.com) "
    "public-domain art & film curation for tellmeohmuse.com"
)
COMMONS_API = "https://commons.wikimedia.org/w/api.php"
COMMONS_HEADERS = {"User-Agent": USER_AGENT}

# ── Target inventory ─────────────────────────────────────────────────────────
# local filename -> Commons page title.
#
# PROVENANCE WARNING: these titles were generated by Gemini, not copied from
# Commons — treat every one as a plausible-sounding guess until `verify` has
# confirmed it. Repair a MISSING title with `discover "<subject keywords>"`,
# pick the right candidate from the manifest it writes, and paste that exact
# title here. Existing downloads are skipped, so re-runs are cheap.

WIKIMEDIA_ASSETS = {
    # Odyssey-scoped picks — human-selected from `select` montages (2026-08-14,
    # the Lion Gate test run): [5] relief close-up, [3] tourist-free gate view
    "lion_gate_relief.jpg": "File:Lion Gate, Relief, Mycenae, 201511.jpg",
    "lion_gate_mycenae.jpg": "File:Lion Gate from the inside. Mycenae, 201514.jpg",
    # Era 1 — archaeological artifacts & pottery (GEMINI GUESSES — verify first)
    "mycenaean_warrior_vase.jpg": "File:Warrior Vase.jpg",
    "mask_of_agamemnon.jpg": "File:Agamemnon mask NAMA Athens Greece.jpg",
    "achilles_ajax_gaming.jpg": "File:Exekias Achilles Ajax MGEt16757.jpg",
    # Era 2 — Baroque & Rococo oils
    "rage_of_achilles_tiepolo.jpg":
        "File:The Rage of Achilles by Giovanni Battista Tiepolo.jpg",
    "sacrifice_of_iphigenia.jpg": "File:Tiepolo, immolazione di ifigenia 01.jpg",
    # Era 3 — Neoclassical & modern
    "triumph_of_achilles_matsch.jpg":
        "File:The Triumph of Achilles by Franz von Matsch.jpg",
    "trojan_horse_procession.jpg":
        "File:Domenico Tiepolo, Procession of the Trojan Horse in Troy.jpg",
}

# Verified on IA 2026-08-14 (Solomon-derived list; see CLAUDE.md film section)
FILM_IDENTIFIERS = [
    "the-trojan-horse-1961",
    "helena-1924",
    "silent-homers-odyssey",                            # L'Odissea (1911)
    "silent-la-caduta-di-troia-aka-the-fall-of-troy",   # Fall of Troy (1911)
    "FuryOfAchilles",                                   # Fury of Achilles (1962)
    "la-legenda-di-enea-1962",                          # Last Glory of Troy (1962)
]

# Preferred IA formats, cheapest first: companion stills, then the smallest
# derivative MP4 stream — never the multi-gigabyte master container.
IA_IMAGE_FORMATS = ["JPEG", "PNG", "Item Image", "Thumbnail"]
IA_VIDEO_FORMATS = ["512Kb MPEG4", "512Kbps MP4", "h.264", "MPEG4"]

# `start` is "HH:MM:SS" (or "MM:SS"). Shipped as None ON PURPOSE: eyeball the
# downloaded MP4s first (scrub in QuickTime / `ffplay`), fill in the moment the
# scene begins, then run `python pipeline.py clips`.
CLIP_SPECS = {
    "the-trojan-horse-1961": [
        {
            "name": "phalanx_formation_6s.mp4",
            "start": None,  # TODO: timestamp of the bronze-armoured phalanx forming up
            "duration": 6,
        },
    ],
    "helena-1924": [
        {
            "name": "fleet_landing_10s.mp4",
            "start": None,  # TODO: timestamp of the naval landing crowd scene
            "duration": 10,
        },
    ],
}


def polite_pause() -> None:
    time.sleep(POLITENESS_DELAY_SECONDS)


def license_is_usable(license_name: str) -> bool:
    """Same acceptance bar as the glossary: PD / CC0 / CC-BY / CC-BY-SA only."""
    name = license_name.lower()
    if "nc" in name or "nd" in name:  # non-commercial / no-derivatives: reject
        return False
    return name.startswith(("public domain", "pd", "cc0", "cc by"))


# ── Phase A: Wikimedia Commons art ───────────────────────────────────────────

def resolve_commons_file(title: str) -> dict | None:
    """Ask the Action API for the original-file URL, license, and identity.

    Returns {"url", "license", "sha1", "pageid"} or None if the title
    doesn't exist. sha1/pageid feed the arrival-time duplicate gates.
    """
    response = requests.get(
        COMMONS_API,
        params={
            "action": "query",
            "titles": title,
            "prop": "imageinfo",
            "iiprop": "url|extmetadata|sha1|size",
            "iiurlwidth": str(MAX_LONG_EDGE),  # ask for a scaled rendition too
            "format": "json",
            "formatversion": "2",
        },
        headers=COMMONS_HEADERS,
        timeout=30,
    )
    response.raise_for_status()
    page = response.json()["query"]["pages"][0]
    if page.get("missing") or "imageinfo" not in page:
        return None
    info = page["imageinfo"][0]
    license_name = (
        info.get("extmetadata", {})
        .get("LicenseShortName", {})
        .get("value", "unknown")
    )
    oversized = (info.get("width") or 0) > MAX_LONG_EDGE
    return {
        "url": info["url"],
        "download_url": (info.get("thumburl") if oversized and
                         info.get("thumburl") else info["url"]),
        "scaled": oversized and bool(info.get("thumburl")),
        "width": info.get("width"),
        "license": license_name,
        "sha1": info.get("sha1"),
        "pageid": page.get("pageid"),
    }


# ── Library ledger: what has already arrived, by identity not filename ───────
# Written on every successful download; consulted BEFORE any download. This is
# the arrival-time duplicate gate — dedupe (Phase E) is the after-the-fact
# audit, the ledger is what stops a duplicate landing at all.

LEDGER_PATH = OUTPUT_DIRECTORY / "library_ledger.json"


def load_ledger() -> dict:
    if LEDGER_PATH.exists():
        return json.loads(LEDGER_PATH.read_text())
    return {"entries": []}


def ledger_record(ledger: dict, **entry) -> None:
    ledger["entries"].append(entry)
    LEDGER_PATH.write_text(json.dumps(ledger, indent=2, ensure_ascii=False))


def ledger_find(ledger: dict, *, sha1=None, pageid=None, title=None):
    normalized = normalize_commons_title(title) if title else None
    for entry in ledger["entries"]:
        if sha1 and entry.get("sha1") == sha1:
            return entry
        if pageid and entry.get("pageid") == pageid:
            return entry
        if normalized and normalize_commons_title(entry.get("title", "")) == normalized:
            return entry
    return None


def run_art_phase() -> None:
    OUTPUT_DIRECTORY.mkdir(parents=True, exist_ok=True)
    ledger = load_ledger()
    glossary = glossary_source_titles()
    print(f"— Phase A: {len(WIKIMEDIA_ASSETS)} Commons artworks —")
    for local_name, title in WIKIMEDIA_ASSETS.items():
        destination = OUTPUT_DIRECTORY / local_name
        if destination.exists():
            print(f"  skip (exists): {local_name}")
            continue

        # Gate 1 (pre-network): this exact file is already on tellmeohmuse
        glossary_key = glossary.get(normalize_commons_title(title))
        if glossary_key:
            print(f"  REFUSED {local_name}: already in the live glossary as "
                  f"{glossary_key!r} — remove it from WIKIMEDIA_ASSETS")
            continue

        # Gate 2 (pre-network): already arrived under another name/term
        if (hit := ledger_find(ledger, title=title)):
            print(f"  REFUSED {local_name}: same title already ingested as "
                  f"{hit['local_name']!r}")
            continue

        try:
            resolved = resolve_commons_file(title)
        except Exception as error:
            print(f"  FAIL resolving {title!r}: {error}")
            polite_pause()
            continue
        polite_pause()  # the API ping was a request too

        if resolved is None:
            print(f"  MISSING on Commons: {title!r} — fix the title in "
                  "WIKIMEDIA_ASSETS (search commons.wikimedia.org) and re-run")
            continue

        # Gate 3 (post-resolve, pre-download): identical bytes or same Commons
        # page already ingested under a DIFFERENT title (re-uploads, renames)
        if (hit := ledger_find(ledger, sha1=resolved["sha1"],
                               pageid=resolved["pageid"])):
            print(f"  REFUSED {local_name}: identical content already "
                  f"ingested as {hit['local_name']!r} (from {hit['title']!r})")
            continue

        rendition = (f"scaled to {MAX_LONG_EDGE}px from {resolved['width']}px"
                     if resolved["scaled"] else "original")
        print(f"  downloading {local_name}  [{resolved['license']}] ({rendition})")
        try:
            with requests.get(
                resolved["download_url"], headers=COMMONS_HEADERS, stream=True,
                timeout=120,
            ) as response:
                response.raise_for_status()
                partial = destination.with_suffix(destination.suffix + ".part")
                with open(partial, "wb") as fh:
                    for chunk in response.iter_content(chunk_size=1 << 16):
                        fh.write(chunk)
                partial.rename(destination)  # atomic: no half-files on interrupt
            ledger_record(ledger, local_name=local_name, title=title,
                          sha1=resolved["sha1"], pageid=resolved["pageid"],
                          license=resolved["license"])
        except Exception as error:
            print(f"  FAIL downloading {local_name}: {error}")
        polite_pause()


# ── Phase 0: verify the (LLM-generated) manifest without downloading ─────────

def run_verify_phase() -> None:
    print(f"— Phase 0: verifying {len(WIKIMEDIA_ASSETS)} manifest titles "
          "(no downloads) —")
    missing = 0
    for local_name, title in WIKIMEDIA_ASSETS.items():
        try:
            resolved = resolve_commons_file(title)
        except Exception as error:
            print(f"  ERROR resolving {title!r}: {error}")
            polite_pause()
            continue
        if resolved is None:
            missing += 1
            print(f"  MISSING  {title!r}  ({local_name}) — repair via "
                  f"`discover`")
        else:
            usable = "ok" if license_is_usable(resolved["license"]) else "LICENSE?"
            print(f"  exists   {title!r}  [{resolved['license']}] {usable}")
        polite_pause()
    print(f"  verdict: {len(WIKIMEDIA_ASSETS) - missing} resolvable, "
          f"{missing} missing")


# ── Phase D: keyword discovery on Commons (candidate manifests only) ─────────

def slugify(term: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in term.strip().lower()).strip("_")


def discover_term(term: str, limit: int = 30) -> dict:
    """One polite search call; returns {term, hits, candidates:[…]}.

    Candidates are license-filtered (PD/CC0/CC-BY/CC-BY-SA) and carry enough
    metadata to be promoted straight into WIKIMEDIA_ASSETS or reviewed later.
    """
    response = requests.get(
        COMMONS_API,
        params={
            "action": "query",
            "generator": "search",
            "gsrsearch": f"{term} filetype:bitmap",
            "gsrnamespace": "6",  # File: namespace
            "gsrlimit": str(limit),
            "prop": "imageinfo",
            "iiprop": "url|extmetadata|size|sha1",
            "format": "json",
            "formatversion": "2",
        },
        headers=COMMONS_HEADERS,
        timeout=30,
    )
    response.raise_for_status()
    pages = response.json().get("query", {}).get("pages", [])
    candidates = []
    for page in pages:
        info = (page.get("imageinfo") or [{}])[0]
        if "url" not in info:
            continue
        metadata = info.get("extmetadata", {})
        license_name = metadata.get("LicenseShortName", {}).get("value", "unknown")
        if not license_is_usable(license_name):
            continue
        candidates.append({
            "title": page["title"],
            # Commons community grading (featured/quality/valued) — a strong
            # prior for clarity & colour fidelity when present
            "assessments": metadata.get("Assessments", {}).get("value", ""),
            "pageid": page.get("pageid"),   # stable identity, survives renames
            "sha1": info.get("sha1"),       # exact-content identity, free from API
            "license": license_name,
            "width": info.get("width"),
            "height": info.get("height"),
            "bytes": info.get("size"),
            "url": info["url"],
            "source_page": info.get("descriptionurl"),
        })
    candidates.sort(key=lambda c: (c["width"] or 0) * (c["height"] or 0),
                    reverse=True)
    return {"term": term, "hits": len(pages), "candidates": candidates}


def run_discover_phase(terms: list[str]) -> None:
    DISCOVERY_DIRECTORY.mkdir(parents=True, exist_ok=True)
    print(f"— Phase D: discovery over {len(terms)} term(s) — candidate "
          "manifests only, no image downloads —")
    for index, term in enumerate(terms, start=1):
        manifest_path = DISCOVERY_DIRECTORY / f"{slugify(term)}.json"
        if manifest_path.exists():  # resumable: one search per term, ever
            print(f"  [{index}/{len(terms)}] skip (manifest exists): {term}")
            continue
        try:
            result = discover_term(term)
        except Exception as error:
            print(f"  [{index}/{len(terms)}] FAIL {term!r}: {error}")
            polite_pause()
            continue
        manifest_path.write_text(
            json.dumps(result, indent=2, ensure_ascii=False))
        print(f"  [{index}/{len(terms)}] {term}: {result['hits']} hits, "
              f"{len(result['candidates'])} license-usable → "
              f"{manifest_path.name}")
        polite_pause()


def load_terms_file(path: Path) -> list[str]:
    terms = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            terms.append(line)
    return terms


# ── Phase 0b: seed the ledger with the live glossary's Commons identities ────
# The glossary gate matches art.json sources by TITLE; seeding writes each of
# those files' Commons sha1 + pageid into library_ledger.json so the identity
# gate also refuses the same artwork arriving under a renamed page or a
# re-uploaded copy. ~582 titles, batched 50 per API request ≈ 12 polite calls.
# Idempotent: already-seeded titles are skipped, so re-runs are near-free.

def run_seed_ledger_phase() -> None:
    if not ART_JSON.exists():
        sys.exit(f"cannot seed: {ART_JSON} not found")
    OUTPUT_DIRECTORY.mkdir(parents=True, exist_ok=True)
    from urllib.parse import unquote

    art = json.loads(ART_JSON.read_text())
    ledger = load_ledger()
    already = {
        normalize_commons_title(entry.get("title", ""))
        for entry in ledger["entries"]
    }

    wanted: dict[str, str] = {}  # normalized title -> art.json key
    titles: dict[str, str] = {}  # normalized title -> query title
    for key, record in art.items():
        source = record.get("source")
        if not (isinstance(source, str) and "File:" in source):
            continue
        query_title = "File:" + unquote(source.split("File:", 1)[1])
        normalized = normalize_commons_title(query_title)
        if normalized in already or normalized in wanted:
            continue  # seeded before, or a shared source (the antique maps)
        wanted[normalized] = key
        titles[normalized] = query_title

    print(f"— Phase 0b: seeding ledger with {len(wanted)} glossary sources "
          f"({len(already)} already present) —")
    batch = list(titles.values())
    missing = 0
    for start in range(0, len(batch), 50):
        chunk = batch[start:start + 50]
        # POST, not GET: 50 long Commons titles overflow URL length limits
        response = requests.post(
            COMMONS_API,
            data={
                "action": "query",
                "titles": "|".join(chunk),
                "prop": "imageinfo",
                "iiprop": "sha1",
                "redirects": "1",  # follow renamed files to their new title
                "format": "json",
                "formatversion": "2",
            },
            headers=COMMONS_HEADERS,
            timeout=60,
        )
        response.raise_for_status()
        query = response.json().get("query", {})
        # map a redirect target back to the title we asked for
        redirected = {
            normalize_commons_title(r["to"]): normalize_commons_title(r["from"])
            for r in query.get("redirects", [])
        }
        for page in query.get("pages", []):
            normalized = normalize_commons_title(page.get("title", ""))
            key = wanted.get(normalized) or wanted.get(
                redirected.get(normalized, ""))
            if key is None:
                continue
            if page.get("missing") or "imageinfo" not in page:
                missing += 1
                print(f"  gone from Commons (title-gate still covers it): "
                      f"{page.get('title')!r} ({key})")
                continue
            info = page["imageinfo"][0]
            ledger_record(ledger, local_name=key, title=page["title"],
                          sha1=info.get("sha1"), pageid=page.get("pageid"),
                          origin="glossary")
        print(f"  batch {start // 50 + 1}: seeded through "
              f"{min(start + 50, len(batch))}/{len(batch)}")
        polite_pause()
    print(f"  done: ledger now {len(load_ledger()['entries'])} entries, "
          f"{missing} source(s) no longer on Commons")


# ── Phase F: select — pick the clearest, best-balanced copy of a work ────────
# For one term's discovery manifest: pull small (512px) renditions of the top
# candidates, score them on measurable proxies, and write a labelled montage
# so the final call is made by EYE. Scores rank, they don't decide:
#   sharpness — variance of an edge filter (blurry scans and upscales score low)
#   clipping  — fraction of pixels at histogram extremes (blown/crushed scans)
#   cast      — spread between R/G/B channel means (yellowed book plates score
#               high; only meaningful RELATIVE to siblings of the same work —
#               genuinely warm artworks are warm in every faithful copy)
#   density   — file bytes per pixel of the original (over-compressed and
#               upscaled files score low)
# plus two metadata priors: Commons assessments (featured/quality) and known
# colour-managed sources ("Google Art Project" etc. in the title).

SELECT_TOP_N = 6
THUMB_WIDTH = 512


def thumb_url(title: str, width: int = THUMB_WIDTH) -> str:
    from urllib.parse import quote
    bare = title.split("File:", 1)[-1]
    return ("https://commons.wikimedia.org/wiki/Special:FilePath/"
            f"{quote(bare)}?width={width}")


def quality_metrics(image) -> dict:
    from PIL import ImageFilter, ImageStat
    rgb = image.convert("RGB")
    gray = rgb.convert("L")
    sharpness = ImageStat.Stat(gray.filter(ImageFilter.FIND_EDGES)).var[0]
    means = ImageStat.Stat(rgb).mean
    cast = max(means) - min(means)
    histogram = gray.histogram()
    total = sum(histogram) or 1
    clipping = (sum(histogram[:4]) + sum(histogram[-4:])) / total
    return {"sharpness": round(sharpness, 1), "cast": round(cast, 1),
            "clipping": round(clipping, 4)}


def run_select_phase(term: str) -> None:
    from PIL import Image, ImageDraw
    import io

    manifest_path = DISCOVERY_DIRECTORY / f"{slugify(term)}.json"
    if not manifest_path.exists():
        sys.exit(f"no discovery manifest for {term!r} — run discover first")
    candidates = json.loads(manifest_path.read_text())["candidates"][:SELECT_TOP_N]
    if not candidates:
        sys.exit(f"manifest for {term!r} has no license-usable candidates")

    select_dir = DISCOVERY_DIRECTORY / "select"
    select_dir.mkdir(parents=True, exist_ok=True)
    print(f"— Phase F: select for {term!r} ({len(candidates)} candidates) —")

    scored, thumbs = [], []
    for index, candidate in enumerate(candidates, start=1):
        try:
            response = requests.get(thumb_url(candidate["title"]),
                                    headers=COMMONS_HEADERS, timeout=60)
            response.raise_for_status()
            image = Image.open(io.BytesIO(response.content))
            image.load()
        except Exception as error:
            print(f"  [{index}] thumb FAIL {candidate['title']!r}: {error}")
            polite_pause()
            continue
        metrics = quality_metrics(image)
        pixels = (candidate.get("width") or 1) * (candidate.get("height") or 1)
        metrics["megapixels"] = round(pixels / 1e6, 1)
        if candidate.get("bytes"):
            metrics["bytes_per_pixel"] = round(candidate["bytes"] / pixels, 3)
        metrics["assessments"] = candidate.get("assessments", "")
        metrics["managed_source"] = any(
            marker in candidate["title"].lower()
            for marker in ("google art project", "rijksmuseum", "met dp",
                           "metropolitan museum", "cleveland museum"))
        scored.append({**candidate, "metrics": metrics})
        thumbs.append((index, image))
        print(f"  [{index}] sharp={metrics['sharpness']:>7.1f} "
              f"cast={metrics['cast']:>5.1f} clip={metrics['clipping']:.3f} "
              f"{metrics['megapixels']:>6.1f}MP "
              f"{'★' if metrics['assessments'] else ' '}"
              f"{'◆' if metrics['managed_source'] else ' '} "
              f"{candidate['title']}")
        polite_pause()

    if thumbs:
        cell = THUMB_WIDTH
        montage = Image.new("RGB", (cell * len(thumbs), cell + 24), "black")
        draw = ImageDraw.Draw(montage)
        for slot, (index, image) in enumerate(thumbs):
            image.thumbnail((cell, cell))
            montage.paste(image, (slot * cell + (cell - image.width) // 2,
                                  (cell - image.height) // 2))
            draw.text((slot * cell + 8, cell + 4), f"[{index}]", fill="white")
        montage_path = select_dir / f"{slugify(term)}_montage.jpg"
        montage.save(montage_path, quality=85)
        print(f"  montage: {montage_path}")

    scores_path = select_dir / f"{slugify(term)}_scores.json"
    scores_path.write_text(json.dumps(scored, indent=2, ensure_ascii=False))
    print(f"  scores:  {scores_path}")
    print("  Decide by VIEWING the montage — scores rank, eyes choose. Then "
          "add the winner's title to WIKIMEDIA_ASSETS.")


# ── Phase B: Internet Archive films ──────────────────────────────────────────

def run_films_phase() -> None:
    if ia is None:
        sys.exit("internetarchive is not installed — pip install -r requirements.txt")
    OUTPUT_DIRECTORY.mkdir(parents=True, exist_ok=True)
    print(f"— Phase B: {len(FILM_IDENTIFIERS)} Internet Archive items —")
    for archive_id in FILM_IDENTIFIERS:
        print(f"  querying manifest for {archive_id}…")
        try:
            item = ia.get_item(archive_id)
            polite_pause()

            # Manifest scan first: report what companion media actually exists
            # so nobody reaches for the master container blindly.
            available = {}
            for f in item.files:
                available.setdefault(f.get("format", "?"), []).append(f.get("name"))
            wanted = [
                fmt for fmt in IA_IMAGE_FORMATS + IA_VIDEO_FORMATS
                if fmt in available
            ]
            if not wanted:
                print(f"  {archive_id}: none of the preferred formats present; "
                      f"manifest has: {sorted(available)}")
                continue
            print(f"  {archive_id}: pulling formats {wanted}")

            # ignore_existing → an interrupted re-run makes no duplicate hits.
            # The client writes into OUTPUT_DIRECTORY/<archive_id>/.
            item.download(
                formats=wanted,
                destdir=str(OUTPUT_DIRECTORY),
                ignore_existing=True,
                verbose=True,
            )
        except Exception as error:
            print(f"  FAIL for {archive_id}: {error}")
        polite_pause()


# ── Phase C: ffmpeg clip cutting (local only, no network) ────────────────────

def find_item_mp4(archive_id: str) -> Path | None:
    item_dir = OUTPUT_DIRECTORY / archive_id
    if not item_dir.is_dir():
        return None
    mp4s = sorted(item_dir.glob("*.mp4"), key=lambda p: p.stat().st_size)
    return mp4s[0] if mp4s else None  # smallest derivative is fine for clips

def run_clips_phase() -> None:
    if subprocess.run(
        ["ffmpeg", "-version"], capture_output=True
    ).returncode != 0:
        sys.exit("ffmpeg not found — brew install ffmpeg")

    CLIPS_DIRECTORY.mkdir(parents=True, exist_ok=True)
    print("— Phase C: clip cutting —")
    for archive_id, specs in CLIP_SPECS.items():
        source = find_item_mp4(archive_id)
        for spec in specs:
            destination = CLIPS_DIRECTORY / spec["name"]
            if destination.exists():
                print(f"  skip (exists): {spec['name']}")
                continue
            if spec["start"] is None:
                print(f"  SKIP {spec['name']}: no start timestamp set — eyeball "
                      f"the {archive_id} MP4, fill in CLIP_SPECS, re-run")
                continue
            if source is None:
                print(f"  SKIP {spec['name']}: no MP4 downloaded for "
                      f"{archive_id} — run the films phase first")
                continue

            # -ss before -i = fast keyframe seek; re-encode for frame-accurate
            # cut points (stream-copy would snap to keyframes seconds away).
            command = [
                "ffmpeg", "-hide_banner", "-loglevel", "warning",
                "-ss", str(spec["start"]),
                "-i", str(source),
                "-t", str(spec["duration"]),
                "-c:v", "libx264", "-preset", "veryfast", "-crf", "20",
                "-c:a", "aac",
                str(destination),
            ]
            print(f"  cutting {spec['name']} from {source.name} "
                  f"@ {spec['start']} (+{spec['duration']}s)")
            result = subprocess.run(command)
            if result.returncode != 0:
                print(f"  FAIL cutting {spec['name']} (ffmpeg exit "
                      f"{result.returncode})")
                destination.unlink(missing_ok=True)


# ── Phase E: dedupe — the no-duplicates guard (local only, no network) ───────
# Layered, cheapest/most-exact first:
#   1. identity     — same Commons pageid or file sha1 claimed by >1 term
#                     (both captured at discovery time, free from the API)
#   2. cross-library— candidate/downloaded titles already present as a
#                     `source` in ../src/data/art.json (the live glossary)
#   3. perceptual   — dHash+aHash sweep (the tellmeohmuse-proven thresholds:
#                     dHash≤12 AND aHash≤18) over downloaded images, including
#                     against ../public/art/*.jpg when present locally, to
#                     catch same-artwork-different-file (crops, rescans,
#                     caption-baked copies) that no identity check can see.
# Perceptual pairs are CANDIDATES — confirm visually before deleting (dark
# images throw false positives; same method note as the glossary's sweep).

ART_JSON = PIPELINE_DIR.parent / "src" / "data" / "art.json"
GLOSSARY_ART_DIR = PIPELINE_DIR.parent / "public" / "art"
DHASH_MAX, AHASH_MAX = 12, 18  # proven thresholds from the glossary sweep


def normalize_commons_title(text: str) -> str:
    """'File:Foo_bar.jpg', a full page URL, or 'Foo bar.jpg' → 'foo bar.jpg'."""
    from urllib.parse import unquote
    text = unquote(text)
    if "File:" in text:
        text = text.split("File:", 1)[1]
    return text.replace("_", " ").strip().lower()


def glossary_source_titles() -> dict[str, str]:
    """normalized Commons title -> art.json key, for the whole live glossary."""
    if not ART_JSON.exists():
        return {}
    art = json.loads(ART_JSON.read_text())
    return {
        normalize_commons_title(record["source"]): key
        for key, record in art.items()
        if isinstance(record.get("source"), str) and "File:" in record["source"]
    }


def image_hashes(path: Path) -> tuple[int, int] | None:
    """(dHash, aHash) of an image file; None if unreadable."""
    from PIL import Image
    try:
        with Image.open(path) as img:
            gray = img.convert("L")
            d = list(gray.resize((9, 8), Image.LANCZOS).getdata())
            a = list(gray.resize((8, 8), Image.LANCZOS).getdata())
    except Exception:
        return None
    dhash = 0
    for row in range(8):
        for col in range(8):
            if d[row * 9 + col] > d[row * 9 + col + 1]:
                dhash |= 1 << (row * 8 + col)
    average = sum(a) / 64
    ahash = sum(1 << i for i, p in enumerate(a) if p > average)
    return dhash, ahash


def hamming(x: int, y: int) -> int:
    return bin(x ^ y).count("1")


def run_dedupe_phase() -> None:
    import hashlib

    report: dict = {}
    hard_failures = 0

    # Layer 1: identity collisions across discovery manifests
    claims_by_sha1: dict[str, list] = {}
    claims_by_pageid: dict[int, list] = {}
    for manifest_path in sorted(DISCOVERY_DIRECTORY.glob("*.json")):
        manifest = json.loads(manifest_path.read_text())
        for candidate in manifest["candidates"]:
            claim = {"term": manifest["term"], "title": candidate["title"]}
            if candidate.get("sha1"):
                claims_by_sha1.setdefault(candidate["sha1"], []).append(claim)
            if candidate.get("pageid"):
                claims_by_pageid.setdefault(candidate["pageid"], []).append(claim)
    identity_collisions = [
        claims for claims in
        list(claims_by_pageid.values()) + list(claims_by_sha1.values())
        if len({c["term"] for c in claims}) > 1
    ]
    report["identity_collisions"] = identity_collisions
    print(f"— Phase E: dedupe —")
    print(f"  layer 1 (identity): {len(identity_collisions)} file(s) claimed "
          "by multiple terms — assign each to ONE term before ingesting")

    # Layer 2: already in the live glossary?
    glossary = glossary_source_titles()
    already_in_glossary = []
    for manifest_path in sorted(DISCOVERY_DIRECTORY.glob("*.json")):
        manifest = json.loads(manifest_path.read_text())
        for candidate in manifest["candidates"]:
            key = glossary.get(normalize_commons_title(candidate["title"]))
            if key:
                already_in_glossary.append(
                    {"term": manifest["term"], "title": candidate["title"],
                     "glossary_key": key})
    for local_name, title in WIKIMEDIA_ASSETS.items():
        key = glossary.get(normalize_commons_title(title))
        if key:
            already_in_glossary.append(
                {"term": "(manifest)", "title": title, "glossary_key": key})
            if (OUTPUT_DIRECTORY / local_name).exists():
                hard_failures += 1
    report["already_in_glossary"] = already_in_glossary
    print(f"  layer 2 (cross-library vs art.json, {len(glossary)} sources): "
          f"{len(already_in_glossary)} match(es) already on tellmeohmuse")

    # Layer 3: exact + perceptual sweep over downloaded files
    downloaded = [
        p for p in OUTPUT_DIRECTORY.rglob("*")
        if p.suffix.lower() in (".jpg", ".jpeg", ".png")
        and CLIPS_DIRECTORY not in p.parents and p.is_file()
    ]
    by_content: dict[str, list[Path]] = {}
    for path in downloaded:
        digest = hashlib.sha1(path.read_bytes()).hexdigest()
        by_content.setdefault(digest, []).append(path)
    exact_dupes = [
        [str(p) for p in paths] for paths in by_content.values()
        if len(paths) > 1
    ]
    hard_failures += len(exact_dupes)
    report["exact_duplicates"] = exact_dupes

    glossary_files = (
        [p for p in GLOSSARY_ART_DIR.glob("*.jpg")
         if not p.name.startswith("map-")]
        if GLOSSARY_ART_DIR.is_dir() else []
    )
    hashed: list[tuple[Path, int, int, bool]] = []
    for path in downloaded:
        if (h := image_hashes(path)):
            hashed.append((path, *h, True))
    for path in glossary_files:
        if (h := image_hashes(path)):
            hashed.append((path, *h, False))
    perceptual_pairs = []
    for i in range(len(hashed)):
        for j in range(i + 1, len(hashed)):
            pi, di, ai, new_i = hashed[i]
            pj, dj, aj, new_j = hashed[j]
            if not (new_i or new_j):
                continue  # glossary-internal pairs are not this pipeline's job
            if hamming(di, dj) <= DHASH_MAX and hamming(ai, aj) <= AHASH_MAX:
                perceptual_pairs.append({
                    "a": str(pi), "b": str(pj),
                    "dhash_distance": hamming(di, dj),
                    "ahash_distance": hamming(ai, aj),
                    "vs_glossary": not (new_i and new_j),
                })
    report["perceptual_candidates"] = perceptual_pairs
    print(f"  layer 3 (perceptual, {len(downloaded)} new + "
          f"{len(glossary_files)} glossary images): {len(exact_dupes)} exact "
          f"dupe group(s), {len(perceptual_pairs)} perceptual pair(s) to "
          "CONFIRM VISUALLY before deleting")

    OUTPUT_DIRECTORY.mkdir(parents=True, exist_ok=True)
    report_path = OUTPUT_DIRECTORY / "dedupe_report.json"
    report_path.write_text(json.dumps(report, indent=2, ensure_ascii=False))
    print(f"  full report: {report_path}")
    if hard_failures:
        sys.exit(f"  DEDUPE FAILED: {hard_failures} hard duplicate(s) — see "
                 "report, delete the losers, re-run")


# ── Entry point ──────────────────────────────────────────────────────────────

PHASES = {
    "verify": [run_verify_phase],
    "seed-ledger": [run_seed_ledger_phase],
    "art": [run_art_phase],
    "films": [run_films_phase],
    "clips": [run_clips_phase],
    "dedupe": [run_dedupe_phase],
    "all": [run_art_phase, run_films_phase, run_clips_phase, run_dedupe_phase],
}

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "phase", nargs="?", default="all",
        choices=list(PHASES) + ["discover", "select"],
        help="which phase to run (default: all)",
    )
    parser.add_argument(
        "keyword", nargs="?",
        help="search term (discover phase, unless --terms-file is given)",
    )
    parser.add_argument(
        "--terms-file", type=Path,
        help="discover: file of search terms, one per line, # comments ok",
    )
    args = parser.parse_args()
    print("Initializing Achaean open-source image & clip extraction pipeline…")

    if args.phase == "discover":
        if args.terms_file:
            terms = load_terms_file(args.terms_file)
        elif args.keyword:
            terms = [args.keyword]
        else:
            parser.error("discover needs a keyword or --terms-file")
        run_discover_phase(terms)
    elif args.phase == "select":
        if not args.keyword:
            parser.error("select needs a term (matching a discovery manifest)")
        run_select_phase(args.keyword)
    else:
        for phase in PHASES[args.phase]:
            phase()
    print("Pipeline sequence executed cleanly.")

if __name__ == "__main__":
    main()
